oc_platform_home:
    path:      /{page}
    defaults: { _controller: testBundle:Advert:index, page: 1 }
    requirements: {page : \d*} 
    
oc_platform_view:
    path:      /advert/{id}
    defaults: { _controller: testBundle:Advert:view }
    requirements: {id: \d+}

oc_platform_add:
    path:      /add
    defaults: { _controller: testBundle:Advert:add }

oc_platform_edit:
    path:      /edit/{id}
    defaults: { _controller: testBundle:Advert:edit }
    requirements: {id: \d+}

oc_platform_delete:
    path:      /delete/{id}
    defaults: { _controller: testBundle:Advert:delete }
    requirements: {id: \d+}


oc_platform_menu:
    path:      /menu
    defaults: { _controller: testBundle:Advert:menu}
    


oc_platform_view_slug:
    path:      /{year}/{slug}.{_format}
    defaults:
        _controller: testBundle:Advert:viewSlug
        format:      html
    requirements:
        year: \d{4}
        format: html|xml

  
  
hello_the_world:
    path:     /hello-world
    defaults: { _controller: testBundle:Advert:hello }

bye_the_world:
    path:     /bye-world
    defaults: { _controller: testBundle:end:endDoor }
